# Generated by Django 4.0 on 2022-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='image',
            field=models.ImageField(default='', upload_to='templates/images'),
        ),
        migrations.AddField(
            model_name='candle',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
