# Generated by Django 4.0 on 2022-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuts_app', '0002_candle_image_candle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='image',
            field=models.ImageField(default='', upload_to='tuts_app/images'),
        ),
    ]
